twnkl/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

from twnkl.apps.main.views import Home, Login, Logout, Register, Profile, Search, PhotoView, PhotosView, UploadPhotoView

urlpatterns = patterns('',
    # Examples:
    url(r'^$', Home.as_view(), name='home'),
    url(r'^login/$', Login.as_view(), name="my_login"),
    url(r'^logout/$', Logout.as_view(), name="my_logout"),
    url(r'^register/$', Register.as_view(), name="register"),
    url(r'^search/$', Search.as_view(), name="search"),
    url(r'^search/(?P<term>\w+)/$', Search.as_view(), name="search"),
    url(r'^photo/(?P<owner>\w+)/(?P<group>\w+)/(?P<pk>\d+)/$', PhotoView.as_view(), name="photo"),
    url(r'^photo/upload/$', UploadPhotoView.as_view(), name="upload_photo"),
    url(r'^photos/$', PhotosView.as_view(), name="photos"),
    url(r'^photos/(?P<owner>\w+)/(?P<group>\w+)/$', PhotosView.as_view(), name="photos"),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/profile/$', Profile.as_view(), name="profile"),
    url(r'^accounts/profile/(?P<username>\w+)/$', Profile.as_view(), name="profile"),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Static-y pages
    #url(r'^about/$', About.as_view(), name="about"),
    #url(r'^contact/$', Contact.as_view(), name='contact'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twnkl/apps/main/models.py
from django.db import models
from django.contrib.auth.models import User
from geoposition.fields import GeopositionField

import os

class Photo(models.Model):
    image = models.ImageField(upload_to="images/")
    name  = models.CharField(max_length=256)
    owner = models.ForeignKey(User)
    groups= models.ManyToManyField('PhotoGroup')
    tags  = models.ManyToManyField('Tag', blank=True)
    loc   = GeopositionField(blank=True)
    dt    = models.DateTimeField(auto_now_add=True)

    def get_first_group(self):
        return self.groups[0].name

    def safe_filename(self):
        return os.path.splitext(os.path.basename(self.image.name))[0]

    def __unicode__(self):
        return str(self.owner) + ":" + str(self.tags) + ":" + str(self.groups)



class Tag(models.Model):
    text = models.CharField(max_length=140)

    def __unicode__(self):
        return self.text

class PhotoGroup(models.Model):
    name = models.CharField(max_length=256)
    owner = models.ForeignKey(User)

    def __unicode__(self):
        return str(self.owner) + ":" + self.name

twnkl/apps/main/forms.py
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.forms.widgets import TextInput, PasswordInput, Textarea, FileInput, Select, CheckboxInput, CheckboxSelectMultiple, HiddenInput, MultipleHiddenInput
from django.forms.models import ModelMultipleChoiceField
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from twnkl.apps.main.models import Photo, PhotoGroup, Tag

class MyMultipleHiddenInput(MultipleHiddenInput):
    def render(self, name, value, **kwargs):
        return super(MyMultipleHiddenInput, self).render(name, value, **kwargs)

class BetterCheckbox(CheckboxSelectMultiple):
    def __init__(self, *args, **kwargs):
        return super(BetterCheckbox, self).__init__(*args, **kwargs)

    def render(self, *args, **kwargs):
        output = super(BetterCheckbox, self).render(*args, **kwargs)
        return mark_safe("<label>Enter groups this photo should be a part of:</label><p>" + output.replace(u'<ul>', u'').replace(u'<li>', u'') + "</p>")


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username",)

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget = TextInput(attrs={'placeholder':'First Name',
                                                          'class':'form-control',
                                                          'required':''})
        self.fields['last_name'].widget = TextInput(attrs={'placeholder':'Last Name',
                                                          'class':'form-control',
                                                          'required':''})
        self.fields['email'].widget = TextInput(attrs={'placeholder':'Email Address',
                                                          'class':'form-control',
                                                          'type':'email',
                                                          'required':''})
        self.fields['username'].widget = TextInput(attrs={'placeholder':'Username',
                                                          'class':'form-control',
                                                          'required':''})
        self.fields['password1'].widget = PasswordInput(attrs={'placeholder':'Password',
                                                          'class':'form-control',
                                                          'required':''})
        self.fields['password2'].widget = PasswordInput(attrs={'placeholder':'Confirm Password',
                                                          'class':'form-control',
                                                          'required':''})

class MyAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(MyAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = TextInput(attrs={'placeholder': 'Username',
                                                          'class': 'form-control',
                                                          'required':''})
        self.fields['password'].widget = PasswordInput(attrs={'placeholder': 'Password',
                                                          'class': 'form-control',
                                                          'required':''})

class MyModelMultipleChoiceField(ModelMultipleChoiceField):
    def clean(self, value):
        pks = []
        for tag_text in value:
            tag, created = Tag.objects.get_or_create(text=tag_text)
            tag.save()
            pks.append(tag.pk)
        return super(MyModelMultipleChoiceField, self).clean(pks)

class PhotoUploadForm(forms.ModelForm):
    tags = MyModelMultipleChoiceField(Tag.objects.all())
 
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(PhotoUploadForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = ""
        self.fields['name'].widget = TextInput(attrs={'placeholder':'Name',
                                                      'class':'form-control',
                                                      'required':''})
        self.fields['tags'].widget = MyMultipleHiddenInput()
        self.fields['tags'].label = "" 
        self.fields['tags'].help_text = ""
        self.fields['tags'].required = False
        self.fields['image'].widget = FileInput(attrs={'style':'display:none',
                                                       'required':''})
        self.fields['image'].label = ""
        self.fields['image'].help_text = ""
        self.fields['groups'].widget = BetterCheckbox(attrs={'required':''},choices=[(o.id, str(o.name)) for o in PhotoGroup.objects.filter(owner__username=user)])
        self.fields['groups'].label = ""
        self.fields['groups'].help_text = ""
        self.fields['groups'].required = True
        #self.fields['loc'].widget = TextInput(attrs={'placeholder': 'Where?',
        #                                             'class':'form-control'})
        #self.fields['loc'].label = ""

    class Meta:
        model = Photo
        exclude = ('owner','loc')

class PhotoUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(PhotoUpdateForm, self).__init__(*args, **kwargs)
        self.fields['tags'].widget = TextInput(attrs={'placeholder':'Enter Tags',
                                                      'class':'form-control'})
        self.fields['tags'].label = "" 
        self.fields['tags'].help_text = ""
        self.fields['name'].label = ""
        self.fields['name'].widget = TextInput(attrs={'placeholder':'Name',
                                                      'class':'form-control'})
        self.fields['groups'].widget = BetterCheckbox(choices=[(o.id, str(o.name)) for o in PhotoGroup.objects.filter(owner__username=user)])
        self.fields['groups'].label = ""
        self.fields['groups'].help_text = ""

    class Meta:
        model = Photo
        exclude = ('owner', 'loc', 'image',)

twnkl/apps/main/views.py
from django.views.generic.base import View, TemplateView, RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.utils.encoding import force_text
from django.contrib.auth.models import User
from django.contrib.auth import login as auth_login
from django.http import HttpResponseRedirect
from twnkl.apps.main.forms import MyAuthenticationForm, RegistrationForm, PhotoUploadForm, PhotoUpdateForm
from twnkl.apps.main.models import Photo, PhotoGroup, Tag
from geoposition import Geoposition
from PIL import Image
from PIL.ExifTags import TAGS

import logging
logger = logging.getLogger(__name__)

class Login(FormView):
    form_class = MyAuthenticationForm
    template_name = "main/signin.html"
    success_url = "/"

    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        return HttpResponseRedirect(self.request.META['HTTP_REFERER'])

    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super(Login, self).dispatch(request, *args, **kwargs)

class Logout(RedirectView):
    url = "/"

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return HttpResponseRedirect(self.get_redirect_url())

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(Logout, self).dispatch(*args, **kwargs)

class Home(ListView):
    template_name = "main/home.html"
    model = Photo

    def get_queryset(self):
        photos = []
        threshold = 0.5
        #for photo in Photo.objects.all():
        #    if pow(pow(float(photo.loc.latitude), 2) + pow(float(photo.loc.longitude), 2), 0.5) < threshold:
        #        photos.append(photo)
        return photos

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['recent_list'] = Photo.objects.order_by('-dt')[0:20]
        if not self.request.user.is_authenticated():
            context['signin_form'] = MyAuthenticationForm()
            context['registration_form'] = RegistrationForm()
        else:
            context['photo_upload_form'] = PhotoUploadForm(user=self.request.user.username)
        return context

class Register(CreateView):
    model = User
    form_class = RegistrationForm
    success_url = "/"

    def form_valid(self, form):
        form.instance.backend = 'django.contrib.auth.backends.ModelBackend'
        self.object = form.save()
        group = PhotoGroup(owner=self.object, name="default")
        group.save()
        auth_login(self.request, self.object)
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return HttpResponseRedirect(self.get_success_url())

class Profile(ListView):
    template_name = "main/profile.html"
    model = PhotoGroup

    def get_queryset(self):
        if 'username' in self.kwargs:
            get_object_or_404(User, username=self.kwargs['username'])
            return PhotoGroup.objects.filter(owner__username=self.kwargs['username'])
        return PhotoGroup.objects.filter(owner__username=self.request.user.username)

class Search(ListView):
    template_name = "main/search_results.html"
    model = Photo

    def get_context_data(self, **kwargs):
        context = super(Search, self).get_context_data(**kwargs)
        context["term"] = self.request.GET.get("term", self.kwargs.get("term", ""))
        return context

    def get_queryset(self):
        return Photo.objects.filter(tags__text__iexact=self.request.GET.get('term', self.kwargs.get("term", "")))

class PhotosView(ListView):
    model = Photo
    template_name = "main/photos_view.html"

    def get_context_data(self, **kwargs):
        context = super(PhotosView, self).get_context_data(**kwargs)
        context['group_name'] = PhotoGroup.objects.get(owner__username=self.kwargs.get('owner', self.request.user.username), name=self.kwargs.get('name', 'default')).name
        return context

    def get_queryset(self):
        group = PhotoGroup.objects.filter(owner__username=self.kwargs.get('owner', self.request.user.username), name=self.kwargs.get('name', 'default'))
        return Photo.objects.filter(groups=group)

class PhotoView(UpdateView):
    model = Photo
    template_name = "main/photo_view.html"
    form_class = PhotoUpdateForm

    def get_success_url(self):
        return force_text(self.request.META['HTTP_REFERER'])

    def get_form_kwargs(self):
        kwargs = super(PhotoView, self).get_form_kwargs()
        kwargs['user'] = self.request.user.username
        return kwargs

class UploadPhotoView(CreateView):
    model = Photo
    success_url = "/accounts/profile/"
    form_class = PhotoUploadForm

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        form.instance.owner = User.objects.get(username=self.request.user)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid()

    def form_valid(self, form):
        exif_data = self.get_exif(form.instance.image)
        if "GPSInfo" in exif_data:
            if 2 in exif_data['GPSInfo'] and 4 in exif_data['GPSInfo']:
                form.instance.loc = Geopostion(exif_data['GPSInfo'][2], exif_data['GPSInfo'][4]) 
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self):
        return HttpResponseRedirect("/")

    def get_form_kwargs(self):
        kwargs = super(UploadPhotoView, self).get_form_kwargs()
        kwargs['user'] = self.request.user.username
        return kwargs

    def get_exif(self, fn):
        ret = {}
        try:
            i = Image.open(fn)
            info = i._getexif()
            for tag, value in info.items():
                decoded = TAGS.get(tag, tag)
                ret[decoded] = value
        except AttributeError as e:
            pass
        return ret

twnkl/templates/main/home.html
{% extends "base.html" %}
{% block title %}{% if user.is_authenticated %}Home{% else %}Sign In{% endif %}{% endblock %}


{% block body %}
    <div class="row row-fluid">
        <div class="container col-sm-6">
        {% include "main/recent_feed.html" %}
        </div>
    {% if user.is_authenticated %}
        {% include "main/upload_photo.html" %}
    {% else %}
        {% include "main/signin.html" %}
    {% endif %}
</div>
{% endblock body %}


{% block script %}
<script type="text/javascript">
$('input[id=id_image]').change( function() {
        $('#photoCover').val($(this).val());
        $('#id_name').val($(this).val().split('\\').pop().split('.').shift());
        });

$('#browse_btn').click( function () {
        $('input[id=id_image]').click();
        });

$('#upload_form').submit( function () {
        $('#id_tags').val($('#id_tags').val() + ")");
        });

var counter = 0;

$('#add_tag_btn').click( function() {
        $('#tag_text').val($('#tag_text').val().replace(/\W/g, ''));
        $('#tags').html($('#tags').html() + '<h2 id="tag_' + $('#tag_text').val() + '"><span class="col-sm-10 label label-default" style="margin: 5px 5px 5px 5px;">' + $('#tag_text').val() + '</span></h2><span id="tag_' + $('#tag_text').val() + '_close" class="col-sm-1">&times;</span>'); 
        $('#tag_' + $('#tag_text').val() + '_close').click( function() {
            $('#tag_' + $('#tag_text').val() + '_close').remove();
            $('#tag_' + $('#tag_text').val()).remove();
            $('input[value=' + $(this).val() + ']').remove();
            });
            $('#tags').prepend('<input id="id_tags_' + counter + '" name="tags" type="hidden" value="' + $('#tag_text').val() + '">');
            counter += 1;
        });


{% for photo in recent_list %}

$("#id_{{ photo.safe_filename }}").popover({ 'html':'true',
                                     'placement':'bottom',
                                     'trigger': 'hover',
                                     'container': 'body',
                                     'content':"<img src='{{ photo.image.url }}' width='100%'>"});
{% endfor %}

{% for photo in object_list %}

$("#id_{{ photo.safe_filename }}").popover({ 'html':'true',
                                     'placement':'bottom',
                                     'trigger': 'hover',
                                     'container': 'body',
                                     'content':"<img src='{{ photo.image.url }}' width='100%'>"});
{% endfor %}
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyBaLOIWJwRzsQWsWBrfdRA4C5XRnzenh5s&sensor=true"></script>
{% include "main/map_location_js.html" %} 
{% endblock script %}

twnkl/templates/main/map_location_js.html
<script type="text/javascript">
var initialLocation;

function initialize() {
    if(navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function (position) {
                window.initialLocation = new google.maps.LatLng(position.coords.latitude,
                    position.coords.longitude);
                var address = new google.maps.Geocoder();
                address.geocode({
                    location: window.initialLocation,
                }, function(result, status) {
                    if( status == google.maps.GeocoderStatus.OK){
                        $('#id_loc').val(result[2]['formatted_address']);
                    }
                    });
                }, function () {
                handleNoGeolocation(true);
                });
    }
    else {
        handleNoGeolocation(false);
    }

    function handleNoGeolocation(errorFlag) {
        if (errorFlag == true ) {
            //alert("Geolocation failed");
            initialLocation = null;
        } else {
            //alert("Your browser doesn't support geolocation.");
            initialLocation = null;
        }
    }

    var input = document.getElementById('id_loc');
    var options = {
        types: ['(cities)'],
        componentRestrictions: {country: 'us'}
    };

    autocomplete = new google.maps.places.Autocomplete(input, options);

    google.maps.event.addListener(autocomplete, 'place_changed', function() {
            var place = autocomplete.getPlace();
            if (!place.geometry) {
                return;
            }
            $("#id_loc").val(place.geometry.location);
        });
    form = document.getElementById('upload_form');
    form.onsubmit = function() {
        document.getElementById('id_loc').value = autocomplete.getPlace().geometry.location;
        form.submit();
    };
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>

twnkl/templates/main/nearby_feed.html
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Photos from nearby your location.</h3>
    </div>
    <div class="panel-body">
    {% for photo in object_list %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <p>
            <a href="{% url "photo" photo.owner.username "default" photo.pk %}" class="thumbnail">
                <img id="id_{{ photo.safe_filename }}" src="{{ photo.image.url }}">
            </a>
            </p>
        </div>
    {% endfor %}
</div>
</div>

twnkl/templates/main/photo_view.html
{% extends "base.html" %}

{% block title %}{{ object.safe_filename }}{% endblock %}

{% block body %}
<div class="row row-fluid">
    <div class="container {% if user == object.owner %}col-sm-9{% else %}col-sm-12{% endif %}">    
        <div class="panel panel-default">    
            <div class="panel-heading">
                <h3 class="panel-title">{{ object.safe_filename }}</h3>
            </div>
            <div class="panel-body">
                <img src="{{ object.image.url }}" style="max-width: 100%">
                <p>
                <a href="{{ object.image.url }}">View Original Image</a>
                </p>
                <div class="container">
                    <div class="container" align="center" style="margin: auto auto auto auto">
                    <span class='st_facebook_large' displayText='Facebook'></span>
                    <span class='st_twitter_large' displayText='Tweet'></span>
                    <span class='st_reddit_large' displayText='Reddit'></span>
                    <span class='st_email_large' displayText='Email'></span>
                </div>
                    <div id="disqus_thread"></div>
                    <script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                    var disqus_shortname = 'twnkl'; // required: replace example with your forum shortname

                    /* * * DON'T EDIT BELOW THIS LINE * * */
                    (function() {
                     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                     dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                     })();
                    </script>
                    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
                </div>
            </div>
        </div>
    </div>
    {% if user == object.owner %}
    <div class="col-sm-3">
        <div class="panel panel-default">    
            <div class="panel-heading">
                <h3 class="panel-title"> Edit {{ object.safe_filename }}</h3>
            </div>
            <div class="panel-body">
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p> 
                    <button type="submit" class="btn btn-success">Update</button>
                    </p>
                </form>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock body %}
{% block script %}
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "149d01d5-0ad6-4269-98aa-540ab47f898d", doNotHash: true, doNotCopy: false, hashAddressBar: false});</script>

<script>
$('#id_tags').val("");
</script>

{% endblock script %}

twnkl/templates/main/photos_view.html
{% extends "base.html" %}
{% block body %}
<div class="row row-fluid">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ group_name }}</h3>
            </div>
            <div class="panel-body">
                <div id="carousel-example-generic" class="carousel slide" style="max-height: 100%">
                    <ol class="carousel-indicators">
                        {% for photo in object_list %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner" style="max-height: 100%">
                        {% for photo in object_list %}
                        <div class="item {% if forloop.first %}active{% endif %}" style="max-height: 100%">
                            <img src="{{ photo.image.url }}" style="max-height: 90%; margin: auto auto auto auto;">
                            <div class="carousel-caption">
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="icon-prev"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="icon-next"></span>
                </a>
                </div>
                <p>
                <div class="container">
                    <div class="container" align="center" style="margin: auto auto auto auto">
                    <span class='st_facebook_large' displayText='Facebook'></span>
                    <span class='st_twitter_large' displayText='Tweet'></span>
                    <span class='st_reddit_large' displayText='Reddit'></span>
                    <span class='st_email_large' displayText='Email'></span>
                </div>
                </p>
                    <div id="disqus_thread"></div>
                    <script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                    var disqus_shortname = 'twnkl'; // required: replace example with your forum shortname

                    /* * * DON'T EDIT BELOW THIS LINE * * */
                    (function() {
                     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                     dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                     })();
                    </script>
                    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
                </div>
            </div>
        </div>
    </div>


</div>

{% endblock body %}

{% block script %}
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "149d01d5-0ad6-4269-98aa-540ab47f898d", doNotHash: true, doNotCopy: false, hashAddressBar: false});</script>
{% endblock script %}

twnkl/templates/main/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block body %}
<div class="row row-fluid">
    <div class="container col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Your Photos</h3>
            </div>
            <div class="panel-body">
                {% for group in object_list %}
                <div class="row row-fluid">
                    <div class="container col-sm-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a href="{% url "photos" group.owner.username group.name %}" class="panel-title">{{ group.name }}</a>
                            </div>
                            <div class="panel-body">
                                {% for photo in group.photo_set.all %}
                                <div class="col-xs-6 col-sm-3 col-md-2 col-lg-1">
                                    <p>
                                    <a href="{% url "photo" photo.owner.username "default" photo.pk %}" class="thumbnail">
                                        <img id="id_{{ photo.safe_filename }}" src="{{ photo.image.url }}">
                                    </a>
                                    </p>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
{% for group in object_list %}
{% for photo in group.photo_set.all %}

$("#id_{{ photo.safe_filename }}").popover({ 'html':'true',
                                     'placement':'bottom',
                                     'trigger': 'hover',
                                     'container': 'body',
                                     'content':"<img src='{{ photo.image.url }}' width='100%'>"});
{% endfor %} 

{% endfor %}
</script>
{% endblock script %}

twnkl/templates/main/recent_feed.html
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Recently Uploaded Photos</h3>
    </div>
    <div class="panel-body">
        {% for photo in recent_list %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <p>
            <a href="{% url "photo" photo.owner.username "default" photo.pk %}" class="thumbnail">
                <img id="id_{{ photo.safe_filename }}" src="{{ photo.image.url }}">
            </a>
            </p>
        </div>
        {% endfor %}
    </div>
</div>